### ISSUE TITLE
failed to compile gem5 and install scons.

### ISSUE THREAD

**Issue by hzspyy** [PolyArch/dsa-framework#17]
I followed the tutorial to use Docker Build image and compile it. I thought I succeeded, but I didn't run through the demo. Originally, I didn't even install scons and didn't compile Gem5

**Comment by LukeLIN-web** [comment]
> I followed the tutorial to use Docker Build image and compile it. I thought I succeeded, but I didn't run through the demo. Originally, I didn't even install scons and didn't compile Gem5

How long you spend on `make -j16`? It takes me more than 19 hours.
In my case, I can install scons and compile Gem5

**Comment by SihaoLiu** [comment]
Hi, thank you for reporting this issue. It should work since it worked during the tutorial. I am not sure whether the Dockerfile is still working. Can you post more detailed error log?

**Comment by hzspyy** [comment]
> Hi, thank you for reporting this issue. It should work since it worked during the tutorial. I am not sure whether the Dockerfile is still working. Can you post more detailed error log?

Later, I downloaded the docker image directly and it worked well.  But I can't give the exact error, too much time has passed. I think maybe I caused the error, I shouldn't use `make -jN`, but 'make -j'.

**Comment by SihaoLiu** [comment]
Good to hear that! Sorry, the version for FCCM2023 tutorial is very out of date and Gem5 installation and scons installation is very hard even for me. We have to stick to a very specific version of scons to make the flow work, which is 3.0.1

**Comment by hzspyy** [comment]
> > I followed the tutorial to use Docker Build image and compile it. I thought I succeeded, but I didn't run through the demo. Originally, I didn't even install scons and didn't compile Gem5
> 
> How long you spend on `make -j16`? It takes me more than 19 hours. In my case, I can install scons and compile Gem5

I forget how long I spent. Error messages are drowned out in parallel compilations. Luckily, the author provides a docker image.
