### ISSUE TITLE
build error in given riscv-gnu-toolchain

### ISSUE THREAD

**Issue by wky9710** [PolyArch/dsa-framework#5]
info:
**********
libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -static-libstdc++ -static-libgcc -o gprof basic_blocks.o call_graph.o cg_arcs.o cg_dfn.o cg_print.o corefile.o gmon_io.o gprof.o hertz.o hist.o source.o search_list.o symtab.o sym_ids.o utils.o i386.o alpha.o vax.o tahoe.o sparc.o mips.o aarch64.o flat_bl.o bsd_callg_bl.o fsf_callg_bl.o  ../bfd/.libs/libbfd.a -L/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib/zlib -lz ../libiberty/libiberty.a -lm -ldl
make[6]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib/gprof'
make[5]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib/gprof'
make[4]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib/gprof'
make[3]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib'
Makefile:848: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build/build-binutils-newlib'
Makefile:375: recipe for target 'stamps/build-binutils-newlib' failed
make[1]: *** [stamps/build-binutils-newlib] Error 2
make[1]: Leaving directory '/home/wky/work/stream-datapath/stream-specialization-stack/riscv-gnu-toolchain/build'
Makefile:39: recipe for target 'riscv-gnu-toolchain' failed
make: *** [riscv-gnu-toolchain] Error 2
**********************
any solutions? or can I use my own riscv toolchain?

**Comment by SihaoLiu** [comment]
Hi, please refer to our latest version of [dsa-framework](https://github.com/PolyArch/dsa-framework). We use the RISC-V GNU under ChipYard
