### ISSUE TITLE
Extracting the DFGs for a recurrence stream has unexpected results

### ISSUE THREAD

**Issue by aparna1996** [PolyArch/dsa-framework#8]
For mm.cc, I did make with EXTRACT=1 (using python dfgs.py), and the resultant dfg file has results in a performance of 0 (with an unroll of 4) using ss_sched. Digging in deeper, I see this is because of the conc pragma not being set in the DFG file. Any suggestions on how can I debug this further? 

The resultant dfg file for mm.cc with unroll of 4 is : [kernel_dfg.txt](https://github.com/PolyArch/dsa-framework/files/5406060/kernel_dfg.txt)

**Comment by SihaoLiu** [comment]
Hi, please refer to our latest version of [dsa-framework](https://github.com/PolyArch/dsa-framework), this infrastructure is much more robust now.
