### ISSUE TITLE
Simple architecture and workload fails

### ISSUE THREAD

**Issue by chiragsakhuja** [PolyArch/dsa-framework#9]
I am trying to use the micro_demo.scala CGRA (from dsa-cgra-gen) to run the workload compile/01_vector_add (from dsa-examples).  I haven't modified any files, and I am on the latest version of dsa-examples, dsa-framework, and all submodules of dsa-framework.

The micro_demo architecture has 2 input ports, 1 output port, and a PE that supports addition and multiplication.  The vector_add workload does a single addition per iteration and is not unrolled, so my understanding is that the micro_demo architecture should be able to execute the workload.

Here are the steps to repro:
1. Run `sbt` from dsa-framework/dsa-cgra-gen
2. Run `runMain real.micro_demo`
3. Modify dsa-examples/common/Makefile to support different CGRAs, like so
```
diff --git a/common/Makefile.compile b/common/Makefile.compile
index c35cda3..8827199 100644
--- a/common/Makefile.compile
+++ b/common/Makefile.compile
@@ -15,13 +15,17 @@ OPT   = opt
 LLC   = llc
 GCC   = riscv64-unknown-elf-g++

+ifndef SBCONFIG
+SBCONFIG = $(SS)/spatial.json
+endif
+
 # Compile pragma hinted high-level language to encoded metadata.
 %.bc: %.cc
        $(CLANG) $< -o $@ $(CLANG_FLAGS) $(IFLAGS) --sysroot=$(RV_ROOT)

 # Transform code regions to be accelerated to decoupled spatial IR.
 dsa-%.bc: %.bc
-       SBCONFIG=$(SS)/spatial.json                                \
+       SBCONFIG=$(SBCONFIG)                                       \
        $(OPT) -load $(SS)/dsa-llvm-project/build/lib/DSAPass.so   \
                   -stream-specialize $< -o $@
```
4. Run `SBCONFIG=$SS/dsa-cgra-gen/my_cgra_div.json ./run.sh O3-dsa-answer.out` from dsa-examples/compile/01_vector_add

I get the following assertion
`dsa-framework/dsa-llvm-project/llvm/lib/Transforms/DSAPass/Transformation.cpp:1254: void DfgFile::EmitAndScheduleDfg(): Assertion Query->MF.EXTRACT failed`.

(Edited for formatting)

**Comment by SihaoLiu** [comment]
Hi, please refer to our latest version of [dsa-framework](https://github.com/PolyArch/dsa-framework)
